// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String testAutomergeDoc({required String key, required String value}) =>
    RustLib.instance.api.crateApiSimpleTestAutomergeDoc(key: key, value: value);

Uint8List mergeAutomergeBinaries({
  required List<int> localBinary,
  required List<int> remoteBinary,
}) => RustLib.instance.api.crateApiSimpleMergeAutomergeBinaries(
  localBinary: localBinary,
  remoteBinary: remoteBinary,
);

Uint8List createAutomergeDocWithData({
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiSimpleCreateAutomergeDocWithData(
  key: key,
  value: value,
);

Uint8List automergeUpdateProperty({
  required List<int> binary,
  required String key,
  required String jsonStr,
}) => RustLib.instance.api.crateApiSimpleAutomergeUpdateProperty(
  binary: binary,
  key: key,
  jsonStr: jsonStr,
);

String automergeGetProperty({required List<int> binary, required String key}) =>
    RustLib.instance.api.crateApiSimpleAutomergeGetProperty(
      binary: binary,
      key: key,
    );
